### PR TITLE
Upgrade to Create-React-App 2

### PR DESCRIPTION
**Pull request by lambrospetrou**
Since CRA 2 version upgraded to Webpack 4 and Babel 7 the existing example does not work out of the box.

I think it's good to keep the example updated since new CRA apps will default to version 2 and it would be sad to have people spending hours trying to find why things do not work.

**Downsides**

- Requiring directly webpack-v3 from `netlify-lambda`. I could not find a better solution to solve this. The actual problem is inside [faundb client](https://medium.com/@danbruder/typeerror-require-is-not-a-function-webpack-faunadb-6e785858d23b) and we need to define a plugin for the webpack version used by `netlify-lambda` to solve the issue.

### CODE REVIEW

**Comment by sw-yx** [comment]
Hi Lambros! thanks for this! I have a ticket to upgrade the webpack version of netlify-lambda too so i dont know if that might help (i'm guessing no). do you want to file a parallel issue over with fauna?

**Comment by lambrospetrou** [comment]
@sw-yx Yes, I was thinking about upgrading `netlify-lambda` as well but I saw several issues already open for that so I didn't want to add more noise there. Hopefully one of those PRs will be merged.

I think they are independent though since only the hack to import webpack3 will need to be removed from this PR which can be done once `netlify-lambda` upgrades.

**Comment by sw-yx** [comment]
hi @lambrospetrou - we have pushed the upgrade of `netlify-lambda`. now for this :)

**Comment by lambrospetrou** [comment]
> hi @lambrospetrou - we have pushed the upgrade of `netlify-lambda`. now for this :)

I upgraded to the latest `netlify-lambda@1.0.2` version so this could be merged I guess.

**Comment by sw-yx** [comment]
thanks @lambrospetrou !

**Pull request merged**
